### PR TITLE
Remove rowCount when not asked for

### PR DESCRIPTION
**Pull request by ryankwagner**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by hiralsp** [comment]
@ryankwagner does this also need to be fixed for other engines?

**Comment by ryankwagner** [comment]
@hiralsp I've only profiled it for Oracle & am taking comments for that, then moving on to other engines.  ATM the only engine sticking out to 'need' the fix is Oracle, but I will make tests for all others and name them as such.

The underlying issue that this fixes is that given a query for only Dims and the desire for DIstinct values, the outer select statement uses the phrase ROWNUM as ROW_NUMBER (noted in OracleQueryGeneratorTest line 2413, in this PR) which makes the distinct statement meaningless.

**Comment by patelh** [comment]
@ryankwagner I'm always afraid these kind of issues will get lost and we'll have different engines optimized differently.

**Comment by ryankwagner** [comment]
Checked Hiva, Druid generators.  Hive doesn't mention Pagination, Druid implements pagination via post processing in the executor.  Postgres has a wrapper for it, but it appears this wrapper uses native rownum which is the same optimization Oracle is gaining here.

**Pull request merged**
