### PR TITLE
Adding support for druid select query

### PR DESCRIPTION
**Pull request by patelh**
Addresses issue #393 

Changes:

- ReportingRequest
  - add support for query type
  - add support for engine specific pagination

- DruidQueryGenerator
  - add support for select query

- DruidQueryExecutor
  - add support for select query
  - fix timeseries query execution
  - increase code coverage
  - standardize execution result, no longer throw exception, return it as part of result

- OracleQueryExecutor
  - standardize execution result, no longer throw exception, return it as part of result

- PrestoQueryExecutor
  - standardize execution result, no longer throw exception, return it as part of result

- QueryPipeline
  - standardize handling of execution result, check result is success, on failure, check result exception

- JsonOutputFormat
  - add support for rendering pagination by engine

### CODE REVIEW

**Comment by pranavbhole** [comment]
Reviewing

**Comment by pavanab4u** [comment]
I've taken a first look. Changes look good.

**Comment by patelh** [comment]
@pranavbhole @pavanab4u added rendering of pagination in jsonoutputstream

**Comment by pavanab4u** [comment]
lgtm

**Comment by patelh** [comment]
@pranavbhole @pavanab4u one of you has to merge, I don't have permissions remember ;)

**Comment by pavanab4u** [comment]
@patelh do you want to increment the version?

**Pull request merged**
